### ISSUE TITLE
No docu, no list of needed modules to install

### ISSUE THREAD

**Issue by marcelpetrick** [ScytheMax/ImageSorter#1]
Please provide some readme.md as quick intro.
Also a list of modules to install (via pip).
And finally the license (GNU GPL  v3.0 for example) under which the project runs.

**Comment by marcelpetrick** [comment]
#

**Comment by marcelpetrick** [comment]
#2

**Comment by ScytheMax** [comment]
issue solved with commits 'added README.md (needs polishing, of course) and expanded the gitignore', 'Merge pull request #2 from marcelpetrick/master' and 'imgSrt-2'
