### ISSUE TITLE
Bug: buttons disappear while switching through images

### ISSUE THREAD

**Issue by marcelpetrick** [ScytheMax/ImageSorter#3]
Reason unknown. Code is unmodified head@master.
Loaded a repository with different images and sometimes all three or just the two which are not under the cursor, disappear.
![imagesorter_disappearingButtons](https://user-images.githubusercontent.com/11920875/94620176-7545b600-02ae-11eb-81a9-b797fabf7ac0.png)
Python 3.7; venv; had to install Pillow.

**Comment by ScytheMax** [comment]
bug fixed with imgSrt-3
